#!/usr/bin/env bash
# Pre-authoring fixture-hash gate.
#
# Asserts the operator's local v1 fixture sha256 matches the value recorded
# in the v1 UI catalog RUN-MANIFEST.md. If they diverge, the catalog
# screenshots and the author's local v1 instance describe different DB
# states — caption interaction notes would describe behavior that wasn't
# captured (or doesn't exist), invalidating the catalog as a reference.
#
# Run before each authoring session. If this fails: STOP. Either reload the
# fixture against a fresh DB, or re-bind the manifest by re-running the
# Phase 2 crawl with the new fixture (a much larger operation).
#
# Usage:
#   scripts/v1-author-precheck.sh
#     [--fixture <path>]   default: ~/Code/COREcare-access/fixtures/v2_catalog_snapshot.json
#     [--manifest <path>]  default: docs/legacy/v1-ui-catalog/RUN-MANIFEST.md
#
# Exit codes:
#   0  fixture sha256 matches manifest
#   1  mismatch (operator must STOP)
#   2  bad invocation (missing fixture/manifest, manifest has no Fixture sha256 line)

set -u

FIXTURE="${HOME}/Code/COREcare-access/fixtures/v2_catalog_snapshot.json"
MANIFEST="docs/legacy/v1-ui-catalog/RUN-MANIFEST.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --fixture)
      if [[ $# -lt 2 ]]; then
        echo "error: --fixture requires a value" >&2
        exit 2
      fi
      FIXTURE="$2"; shift 2 ;;
    --manifest)
      if [[ $# -lt 2 ]]; then
        echo "error: --manifest requires a value" >&2
        exit 2
      fi
      MANIFEST="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *)
      echo "error: unknown arg: $1" >&2
      exit 2 ;;
  esac
done

if [[ ! -f "$FIXTURE" ]]; then
  echo "error: fixture file not found: $FIXTURE" >&2
  exit 2
fi
if [[ ! -f "$MANIFEST" ]]; then
  echo "error: manifest file not found: $MANIFEST" >&2
  exit 2
fi

# Extract `**Fixture sha256:** <hash>` from manifest. The manifest is
# generated by tools/v1-screenshot-catalog/crawl.ts; the field is bold
# markdown bold-key style.
EXPECTED=$(grep -E '^\*\*Fixture sha256:\*\*[[:space:]]+[0-9a-f]{64}' "$MANIFEST" \
             | head -1 \
             | sed -E 's/^\*\*Fixture sha256:\*\*[[:space:]]+//' \
             | tr -d '[:space:]')

if [[ -z "$EXPECTED" ]]; then
  echo "error: manifest has no '**Fixture sha256:**' line: $MANIFEST" >&2
  exit 2
fi

# shasum is BSD/macOS; sha256sum is GNU. Prefer shasum because the runbook
# already standardizes on it; fall back to sha256sum.
if command -v shasum >/dev/null 2>&1; then
  ACTUAL=$(shasum -a 256 "$FIXTURE" | awk '{print $1}')
elif command -v sha256sum >/dev/null 2>&1; then
  ACTUAL=$(sha256sum "$FIXTURE" | awk '{print $1}')
else
  echo "error: neither shasum nor sha256sum is available" >&2
  exit 2
fi

if [[ "$ACTUAL" == "$EXPECTED" ]]; then
  echo "OK: fixture sha256 matches manifest"
  echo "  fixture:  $FIXTURE"
  echo "  manifest: $MANIFEST"
  echo "  sha256:   $ACTUAL"
  exit 0
fi

echo "STOP: fixture sha256 does NOT match manifest."
echo ""
echo "  fixture:        $FIXTURE"
echo "  manifest:       $MANIFEST"
echo "  manifest sha:   $EXPECTED"
echo "  actual sha:     $ACTUAL"
echo ""
echo "Authoring against a divergent fixture invalidates the catalog as a reference."
echo "Either:"
echo "  1. Reload the fixture against a fresh DB to restore the manifest sha, OR"
echo "  2. Re-run Phase 2 crawl with the new fixture (regenerates the manifest)."
exit 1
